// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: contracts/protobuf/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InventoryId       string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ProductId         string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId         string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Sku               string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,5,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	ReservedQuantity  int32                  `protobuf:"varint,6,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	LowStockThreshold int32                  `protobuf:"varint,7,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryItem) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *InventoryItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InventoryItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *InventoryItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryItem) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *InventoryItem) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *InventoryItem) GetLowStockThreshold() int32 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

func (x *InventoryItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *InventoryItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	InventoryId   string                 `protobuf:"bytes,4,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetInventoryRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *GetInventoryRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetInventoryRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *InventoryItem         `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryResponse) GetInventory() *InventoryItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type CreateInventoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MerchantId        string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ProductId         string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId         string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Sku               string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	InitialQuantity   int32                  `protobuf:"varint,5,opt,name=initial_quantity,json=initialQuantity,proto3" json:"initial_quantity,omitempty"`
	LowStockThreshold int32                  `protobuf:"varint,6,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateInventoryRequest) Reset() {
	*x = CreateInventoryRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryRequest) ProtoMessage() {}

func (x *CreateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInventoryRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateInventoryRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateInventoryRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *CreateInventoryRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateInventoryRequest) GetInitialQuantity() int32 {
	if x != nil {
		return x.InitialQuantity
	}
	return 0
}

func (x *CreateInventoryRequest) GetLowStockThreshold() int32 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

type CreateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *InventoryItem         `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryResponse) Reset() {
	*x = CreateInventoryResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryResponse) ProtoMessage() {}

func (x *CreateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryResponse.ProtoReflect.Descriptor instead.
func (*CreateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInventoryResponse) GetInventory() *InventoryItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type RestockInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	InventoryId   string                 `protobuf:"bytes,4,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockInventoryRequest) Reset() {
	*x = RestockInventoryRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockInventoryRequest) ProtoMessage() {}

func (x *RestockInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockInventoryRequest.ProtoReflect.Descriptor instead.
func (*RestockInventoryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *RestockInventoryRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RestockInventoryRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RestockInventoryRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *RestockInventoryRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *RestockInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RestockInventoryRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *RestockInventoryRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RestockInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *InventoryItem         `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockInventoryResponse) Reset() {
	*x = RestockInventoryResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockInventoryResponse) ProtoMessage() {}

func (x *RestockInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockInventoryResponse.ProtoReflect.Descriptor instead.
func (*RestockInventoryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *RestockInventoryResponse) GetInventory() *InventoryItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *RestockInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StockItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,2,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	ReservedQuantity  int32                  `protobuf:"varint,3,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *StockItem) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *GetStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *StockItem             `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *GetStockResponse) GetStock() *StockItem {
	if x != nil {
		return x.Stock
	}
	return nil
}

type ReservationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationItem) Reset() {
	*x = ReservationItem{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationItem) ProtoMessage() {}

func (x *ReservationItem) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationItem.ProtoReflect.Descriptor instead.
func (*ReservationItem) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ReservationItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReservationItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ReservationItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveStockRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items             []*ReservationItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ExpirationMinutes int32                  `protobuf:"varint,3,opt,name=expiration_minutes,json=expirationMinutes,proto3" json:"expiration_minutes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetItems() []*ReservationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveStockRequest) GetExpirationMinutes() int32 {
	if x != nil {
		return x.ExpirationMinutes
	}
	return 0
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *ReserveStockResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveStockResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseStockRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseStockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *ReleaseStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReleaseExpiredReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseExpiredReservationsRequest) Reset() {
	*x = ReleaseExpiredReservationsRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseExpiredReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseExpiredReservationsRequest) ProtoMessage() {}

func (x *ReleaseExpiredReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseExpiredReservationsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseExpiredReservationsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{15}
}

type ReleaseExpiredReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReleasedCount int32                  `protobuf:"varint,1,opt,name=released_count,json=releasedCount,proto3" json:"released_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseExpiredReservationsResponse) Reset() {
	*x = ReleaseExpiredReservationsResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseExpiredReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseExpiredReservationsResponse) ProtoMessage() {}

func (x *ReleaseExpiredReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseExpiredReservationsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseExpiredReservationsResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *ReleaseExpiredReservationsResponse) GetReleasedCount() int32 {
	if x != nil {
		return x.ReleasedCount
	}
	return 0
}

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	VariantId     string                 `protobuf:"bytes,4,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateStockRequest) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *UpdateStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateStockRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *StockItem             `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStockResponse) GetStock() *StockItem {
	if x != nil {
		return x.Stock
	}
	return nil
}

type CommitStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStockRequest) Reset() {
	*x = CommitStockRequest{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStockRequest) ProtoMessage() {}

func (x *CommitStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStockRequest.ProtoReflect.Descriptor instead.
func (*CommitStockRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{19}
}

func (x *CommitStockRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CommitStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CommitStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStockResponse) Reset() {
	*x = CommitStockResponse{}
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStockResponse) ProtoMessage() {}

func (x *CommitStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_inventory_inventory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStockResponse.ProtoReflect.Descriptor instead.
func (*CommitStockResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP(), []int{20}
}

func (x *CommitStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_contracts_protobuf_inventory_inventory_proto protoreflect.FileDescriptor

const file_contracts_protobuf_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	",contracts/protobuf/inventory/inventory.proto\x12\x13gocart.inventory.v1\"\xcc\x02\n" +
	"\rInventoryItem\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12-\n" +
	"\x12available_quantity\x18\x05 \x01(\x05R\x11availableQuantity\x12+\n" +
	"\x11reserved_quantity\x18\x06 \x01(\x05R\x10reservedQuantity\x12.\n" +
	"\x13low_stock_threshold\x18\a \x01(\x05R\x11lowStockThreshold\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\x97\x01\n" +
	"\x13GetInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\finventory_id\x18\x04 \x01(\tR\vinventoryId\"X\n" +
	"\x14GetInventoryResponse\x12@\n" +
	"\tinventory\x18\x01 \x01(\v2\".gocart.inventory.v1.InventoryItemR\tinventory\"\xe4\x01\n" +
	"\x16CreateInventoryRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12)\n" +
	"\x10initial_quantity\x18\x05 \x01(\x05R\x0finitialQuantity\x12.\n" +
	"\x13low_stock_threshold\x18\x06 \x01(\x05R\x11lowStockThreshold\"[\n" +
	"\x17CreateInventoryResponse\x12@\n" +
	"\tinventory\x18\x01 \x01(\v2\".gocart.inventory.v1.InventoryItemR\tinventory\"\xf0\x01\n" +
	"\x17RestockInventoryRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12!\n" +
	"\finventory_id\x18\x04 \x01(\tR\vinventoryId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"v\n" +
	"\x18RestockInventoryResponse\x12@\n" +
	"\tinventory\x18\x01 \x01(\v2\".gocart.inventory.v1.InventoryItemR\tinventory\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x86\x01\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12-\n" +
	"\x12available_quantity\x18\x02 \x01(\x05R\x11availableQuantity\x12+\n" +
	"\x11reserved_quantity\x18\x03 \x01(\x05R\x10reservedQuantity\"0\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"H\n" +
	"\x10GetStockResponse\x124\n" +
	"\x05stock\x18\x01 \x01(\v2\x1e.gocart.inventory.v1.StockItemR\x05stock\"k\n" +
	"\x0fReservationItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x9b\x01\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12:\n" +
	"\x05items\x18\x02 \x03(\v2$.gocart.inventory.v1.ReservationItemR\x05items\x12-\n" +
	"\x12expiration_minutes\x18\x03 \x01(\x05R\x11expirationMinutes\"v\n" +
	"\x14ReserveStockResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"o\n" +
	"\x13ReleaseStockRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"0\n" +
	"\x14ReleaseStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"!ReleaseExpiredReservationsRequest\"K\n" +
	"\"ReleaseExpiredReservationsResponse\x12%\n" +
	"\x0ereleased_count\x18\x01 \x01(\x05R\rreleasedCount\"\x91\x01\n" +
	"\x12UpdateStockRequest\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x04 \x01(\tR\tvariantId\"K\n" +
	"\x13UpdateStockResponse\x124\n" +
	"\x05stock\x18\x01 \x01(\v2\x1e.gocart.inventory.v1.StockItemR\x05stock\"V\n" +
	"\x12CommitStockRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"/\n" +
	"\x13CommitStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcd\a\n" +
	"\x10InventoryService\x12c\n" +
	"\fGetInventory\x12(.gocart.inventory.v1.GetInventoryRequest\x1a).gocart.inventory.v1.GetInventoryResponse\x12l\n" +
	"\x0fCreateInventory\x12+.gocart.inventory.v1.CreateInventoryRequest\x1a,.gocart.inventory.v1.CreateInventoryResponse\x12o\n" +
	"\x10RestockInventory\x12,.gocart.inventory.v1.RestockInventoryRequest\x1a-.gocart.inventory.v1.RestockInventoryResponse\x12W\n" +
	"\bGetStock\x12$.gocart.inventory.v1.GetStockRequest\x1a%.gocart.inventory.v1.GetStockResponse\x12c\n" +
	"\fReserveStock\x12(.gocart.inventory.v1.ReserveStockRequest\x1a).gocart.inventory.v1.ReserveStockResponse\x12c\n" +
	"\fReleaseStock\x12(.gocart.inventory.v1.ReleaseStockRequest\x1a).gocart.inventory.v1.ReleaseStockResponse\x12\x8d\x01\n" +
	"\x1aReleaseExpiredReservations\x126.gocart.inventory.v1.ReleaseExpiredReservationsRequest\x1a7.gocart.inventory.v1.ReleaseExpiredReservationsResponse\x12`\n" +
	"\vUpdateStock\x12'.gocart.inventory.v1.UpdateStockRequest\x1a(.gocart.inventory.v1.UpdateStockResponse\x12`\n" +
	"\vCommitStock\x12'.gocart.inventory.v1.CommitStockRequest\x1a(.gocart.inventory.v1.CommitStockResponseBNZLgithub.com/marees-godev/GoCart-Server/contracts/protobuf/inventory;inventoryb\x06proto3"

var (
	file_contracts_protobuf_inventory_inventory_proto_rawDescOnce sync.Once
	file_contracts_protobuf_inventory_inventory_proto_rawDescData []byte
)

func file_contracts_protobuf_inventory_inventory_proto_rawDescGZIP() []byte {
	file_contracts_protobuf_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_contracts_protobuf_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_protobuf_inventory_inventory_proto_rawDesc), len(file_contracts_protobuf_inventory_inventory_proto_rawDesc)))
	})
	return file_contracts_protobuf_inventory_inventory_proto_rawDescData
}

var file_contracts_protobuf_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_contracts_protobuf_inventory_inventory_proto_goTypes = []any{
	(*InventoryItem)(nil),                      // 0: gocart.inventory.v1.InventoryItem
	(*GetInventoryRequest)(nil),                // 1: gocart.inventory.v1.GetInventoryRequest
	(*GetInventoryResponse)(nil),               // 2: gocart.inventory.v1.GetInventoryResponse
	(*CreateInventoryRequest)(nil),             // 3: gocart.inventory.v1.CreateInventoryRequest
	(*CreateInventoryResponse)(nil),            // 4: gocart.inventory.v1.CreateInventoryResponse
	(*RestockInventoryRequest)(nil),            // 5: gocart.inventory.v1.RestockInventoryRequest
	(*RestockInventoryResponse)(nil),           // 6: gocart.inventory.v1.RestockInventoryResponse
	(*StockItem)(nil),                          // 7: gocart.inventory.v1.StockItem
	(*GetStockRequest)(nil),                    // 8: gocart.inventory.v1.GetStockRequest
	(*GetStockResponse)(nil),                   // 9: gocart.inventory.v1.GetStockResponse
	(*ReservationItem)(nil),                    // 10: gocart.inventory.v1.ReservationItem
	(*ReserveStockRequest)(nil),                // 11: gocart.inventory.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil),               // 12: gocart.inventory.v1.ReserveStockResponse
	(*ReleaseStockRequest)(nil),                // 13: gocart.inventory.v1.ReleaseStockRequest
	(*ReleaseStockResponse)(nil),               // 14: gocart.inventory.v1.ReleaseStockResponse
	(*ReleaseExpiredReservationsRequest)(nil),  // 15: gocart.inventory.v1.ReleaseExpiredReservationsRequest
	(*ReleaseExpiredReservationsResponse)(nil), // 16: gocart.inventory.v1.ReleaseExpiredReservationsResponse
	(*UpdateStockRequest)(nil),                 // 17: gocart.inventory.v1.UpdateStockRequest
	(*UpdateStockResponse)(nil),                // 18: gocart.inventory.v1.UpdateStockResponse
	(*CommitStockRequest)(nil),                 // 19: gocart.inventory.v1.CommitStockRequest
	(*CommitStockResponse)(nil),                // 20: gocart.inventory.v1.CommitStockResponse
}
var file_contracts_protobuf_inventory_inventory_proto_depIdxs = []int32{
	0,  // 0: gocart.inventory.v1.GetInventoryResponse.inventory:type_name -> gocart.inventory.v1.InventoryItem
	0,  // 1: gocart.inventory.v1.CreateInventoryResponse.inventory:type_name -> gocart.inventory.v1.InventoryItem
	0,  // 2: gocart.inventory.v1.RestockInventoryResponse.inventory:type_name -> gocart.inventory.v1.InventoryItem
	7,  // 3: gocart.inventory.v1.GetStockResponse.stock:type_name -> gocart.inventory.v1.StockItem
	10, // 4: gocart.inventory.v1.ReserveStockRequest.items:type_name -> gocart.inventory.v1.ReservationItem
	7,  // 5: gocart.inventory.v1.UpdateStockResponse.stock:type_name -> gocart.inventory.v1.StockItem
	1,  // 6: gocart.inventory.v1.InventoryService.GetInventory:input_type -> gocart.inventory.v1.GetInventoryRequest
	3,  // 7: gocart.inventory.v1.InventoryService.CreateInventory:input_type -> gocart.inventory.v1.CreateInventoryRequest
	5,  // 8: gocart.inventory.v1.InventoryService.RestockInventory:input_type -> gocart.inventory.v1.RestockInventoryRequest
	8,  // 9: gocart.inventory.v1.InventoryService.GetStock:input_type -> gocart.inventory.v1.GetStockRequest
	11, // 10: gocart.inventory.v1.InventoryService.ReserveStock:input_type -> gocart.inventory.v1.ReserveStockRequest
	13, // 11: gocart.inventory.v1.InventoryService.ReleaseStock:input_type -> gocart.inventory.v1.ReleaseStockRequest
	15, // 12: gocart.inventory.v1.InventoryService.ReleaseExpiredReservations:input_type -> gocart.inventory.v1.ReleaseExpiredReservationsRequest
	17, // 13: gocart.inventory.v1.InventoryService.UpdateStock:input_type -> gocart.inventory.v1.UpdateStockRequest
	19, // 14: gocart.inventory.v1.InventoryService.CommitStock:input_type -> gocart.inventory.v1.CommitStockRequest
	2,  // 15: gocart.inventory.v1.InventoryService.GetInventory:output_type -> gocart.inventory.v1.GetInventoryResponse
	4,  // 16: gocart.inventory.v1.InventoryService.CreateInventory:output_type -> gocart.inventory.v1.CreateInventoryResponse
	6,  // 17: gocart.inventory.v1.InventoryService.RestockInventory:output_type -> gocart.inventory.v1.RestockInventoryResponse
	9,  // 18: gocart.inventory.v1.InventoryService.GetStock:output_type -> gocart.inventory.v1.GetStockResponse
	12, // 19: gocart.inventory.v1.InventoryService.ReserveStock:output_type -> gocart.inventory.v1.ReserveStockResponse
	14, // 20: gocart.inventory.v1.InventoryService.ReleaseStock:output_type -> gocart.inventory.v1.ReleaseStockResponse
	16, // 21: gocart.inventory.v1.InventoryService.ReleaseExpiredReservations:output_type -> gocart.inventory.v1.ReleaseExpiredReservationsResponse
	18, // 22: gocart.inventory.v1.InventoryService.UpdateStock:output_type -> gocart.inventory.v1.UpdateStockResponse
	20, // 23: gocart.inventory.v1.InventoryService.CommitStock:output_type -> gocart.inventory.v1.CommitStockResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_contracts_protobuf_inventory_inventory_proto_init() }
func file_contracts_protobuf_inventory_inventory_proto_init() {
	if File_contracts_protobuf_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_protobuf_inventory_inventory_proto_rawDesc), len(file_contracts_protobuf_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_protobuf_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_contracts_protobuf_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_contracts_protobuf_inventory_inventory_proto_msgTypes,
	}.Build()
	File_contracts_protobuf_inventory_inventory_proto = out.File
	file_contracts_protobuf_inventory_inventory_proto_goTypes = nil
	file_contracts_protobuf_inventory_inventory_proto_depIdxs = nil
}
