// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.5
// source: contracts/protobuf/delivery/delivery.proto

package delivery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delivery struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId             string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrackingNumber      string                 `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	CourierName         string                 `protobuf:"bytes,4,opt,name=courier_name,json=courierName,proto3" json:"courier_name,omitempty"`
	Status              string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	EstimatedDeliveryAt string                 `protobuf:"bytes,6,opt,name=estimated_delivery_at,json=estimatedDeliveryAt,proto3" json:"estimated_delivery_at,omitempty"`
	DeliveredAt         string                 `protobuf:"bytes,7,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Delivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delivery) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Delivery) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Delivery) GetCourierName() string {
	if x != nil {
		return x.CourierName
	}
	return ""
}

func (x *Delivery) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Delivery) GetEstimatedDeliveryAt() string {
	if x != nil {
		return x.EstimatedDeliveryAt
	}
	return ""
}

func (x *Delivery) GetDeliveredAt() string {
	if x != nil {
		return x.DeliveredAt
	}
	return ""
}

type CreateDeliveryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CourierName     string                 `protobuf:"bytes,2,opt,name=courier_name,json=courierName,proto3" json:"courier_name,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,3,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDeliveryRequest) Reset() {
	*x = CreateDeliveryRequest{}
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryRequest) ProtoMessage() {}

func (x *CreateDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryRequest.ProtoReflect.Descriptor instead.
func (*CreateDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateDeliveryRequest) GetCourierName() string {
	if x != nil {
		return x.CourierName
	}
	return ""
}

func (x *CreateDeliveryRequest) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

type CreateDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeliveryResponse) Reset() {
	*x = CreateDeliveryResponse{}
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryResponse) ProtoMessage() {}

func (x *CreateDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryResponse.ProtoReflect.Descriptor instead.
func (*CreateDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeliveryResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type GetDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryRequest) Reset() {
	*x = GetDeliveryRequest{}
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryRequest) ProtoMessage() {}

func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryResponse) Reset() {
	*x = GetDeliveryResponse{}
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryResponse) ProtoMessage() {}

func (x *GetDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveryResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type UpdateDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDeliveryStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type UpdateDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusResponse) Reset() {
	*x = UpdateDeliveryStatusResponse{}
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusResponse) ProtoMessage() {}

func (x *UpdateDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_delivery_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDeliveryStatusResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

var File_contracts_protobuf_delivery_delivery_proto protoreflect.FileDescriptor

const file_contracts_protobuf_delivery_delivery_proto_rawDesc = "" +
	"\n" +
	"*contracts/protobuf/delivery/delivery.proto\x12\x12gocart.delivery.v1\"\xf0\x01\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\x12!\n" +
	"\fcourier_name\x18\x04 \x01(\tR\vcourierName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x122\n" +
	"\x15estimated_delivery_at\x18\x06 \x01(\tR\x13estimatedDeliveryAt\x12!\n" +
	"\fdelivered_at\x18\a \x01(\tR\vdeliveredAt\"\x80\x01\n" +
	"\x15CreateDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\fcourier_name\x18\x02 \x01(\tR\vcourierName\x12)\n" +
	"\x10shipping_address\x18\x03 \x01(\tR\x0fshippingAddress\"R\n" +
	"\x16CreateDeliveryResponse\x128\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1c.gocart.delivery.v1.DeliveryR\bdelivery\"$\n" +
	"\x12GetDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x13GetDeliveryResponse\x128\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1c.gocart.delivery.v1.DeliveryR\bdelivery\"a\n" +
	"\x1bUpdateDeliveryStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"X\n" +
	"\x1cUpdateDeliveryStatusResponse\x128\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1c.gocart.delivery.v1.DeliveryR\bdelivery2\xd5\x02\n" +
	"\x0fDeliveryService\x12g\n" +
	"\x0eCreateDelivery\x12).gocart.delivery.v1.CreateDeliveryRequest\x1a*.gocart.delivery.v1.CreateDeliveryResponse\x12^\n" +
	"\vGetDelivery\x12&.gocart.delivery.v1.GetDeliveryRequest\x1a'.gocart.delivery.v1.GetDeliveryResponse\x12y\n" +
	"\x14UpdateDeliveryStatus\x12/.gocart.delivery.v1.UpdateDeliveryStatusRequest\x1a0.gocart.delivery.v1.UpdateDeliveryStatusResponseBLZJgithub.com/marees-godev/GoCart-Server/contracts/protobuf/delivery;deliveryb\x06proto3"

var (
	file_contracts_protobuf_delivery_delivery_proto_rawDescOnce sync.Once
	file_contracts_protobuf_delivery_delivery_proto_rawDescData []byte
)

func file_contracts_protobuf_delivery_delivery_proto_rawDescGZIP() []byte {
	file_contracts_protobuf_delivery_delivery_proto_rawDescOnce.Do(func() {
		file_contracts_protobuf_delivery_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_protobuf_delivery_delivery_proto_rawDesc), len(file_contracts_protobuf_delivery_delivery_proto_rawDesc)))
	})
	return file_contracts_protobuf_delivery_delivery_proto_rawDescData
}

var file_contracts_protobuf_delivery_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_contracts_protobuf_delivery_delivery_proto_goTypes = []any{
	(*Delivery)(nil),                     // 0: gocart.delivery.v1.Delivery
	(*CreateDeliveryRequest)(nil),        // 1: gocart.delivery.v1.CreateDeliveryRequest
	(*CreateDeliveryResponse)(nil),       // 2: gocart.delivery.v1.CreateDeliveryResponse
	(*GetDeliveryRequest)(nil),           // 3: gocart.delivery.v1.GetDeliveryRequest
	(*GetDeliveryResponse)(nil),          // 4: gocart.delivery.v1.GetDeliveryResponse
	(*UpdateDeliveryStatusRequest)(nil),  // 5: gocart.delivery.v1.UpdateDeliveryStatusRequest
	(*UpdateDeliveryStatusResponse)(nil), // 6: gocart.delivery.v1.UpdateDeliveryStatusResponse
}
var file_contracts_protobuf_delivery_delivery_proto_depIdxs = []int32{
	0, // 0: gocart.delivery.v1.CreateDeliveryResponse.delivery:type_name -> gocart.delivery.v1.Delivery
	0, // 1: gocart.delivery.v1.GetDeliveryResponse.delivery:type_name -> gocart.delivery.v1.Delivery
	0, // 2: gocart.delivery.v1.UpdateDeliveryStatusResponse.delivery:type_name -> gocart.delivery.v1.Delivery
	1, // 3: gocart.delivery.v1.DeliveryService.CreateDelivery:input_type -> gocart.delivery.v1.CreateDeliveryRequest
	3, // 4: gocart.delivery.v1.DeliveryService.GetDelivery:input_type -> gocart.delivery.v1.GetDeliveryRequest
	5, // 5: gocart.delivery.v1.DeliveryService.UpdateDeliveryStatus:input_type -> gocart.delivery.v1.UpdateDeliveryStatusRequest
	2, // 6: gocart.delivery.v1.DeliveryService.CreateDelivery:output_type -> gocart.delivery.v1.CreateDeliveryResponse
	4, // 7: gocart.delivery.v1.DeliveryService.GetDelivery:output_type -> gocart.delivery.v1.GetDeliveryResponse
	6, // 8: gocart.delivery.v1.DeliveryService.UpdateDeliveryStatus:output_type -> gocart.delivery.v1.UpdateDeliveryStatusResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contracts_protobuf_delivery_delivery_proto_init() }
func file_contracts_protobuf_delivery_delivery_proto_init() {
	if File_contracts_protobuf_delivery_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_protobuf_delivery_delivery_proto_rawDesc), len(file_contracts_protobuf_delivery_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_protobuf_delivery_delivery_proto_goTypes,
		DependencyIndexes: file_contracts_protobuf_delivery_delivery_proto_depIdxs,
		MessageInfos:      file_contracts_protobuf_delivery_delivery_proto_msgTypes,
	}.Build()
	File_contracts_protobuf_delivery_delivery_proto = out.File
	file_contracts_protobuf_delivery_delivery_proto_goTypes = nil
	file_contracts_protobuf_delivery_delivery_proto_depIdxs = nil
}
