// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: contracts/protobuf/merchant/merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantStatus int32

const (
	MerchantStatus_PENDING   MerchantStatus = 0
	MerchantStatus_APPROVED  MerchantStatus = 1
	MerchantStatus_REJECTED  MerchantStatus = 2
	MerchantStatus_SUSPENDED MerchantStatus = 3
)

// Enum value maps for MerchantStatus.
var (
	MerchantStatus_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "REJECTED",
		3: "SUSPENDED",
	}
	MerchantStatus_value = map[string]int32{
		"PENDING":   0,
		"APPROVED":  1,
		"REJECTED":  2,
		"SUSPENDED": 3,
	}
)

func (x MerchantStatus) Enum() *MerchantStatus {
	p := new(MerchantStatus)
	*p = x
	return p
}

func (x MerchantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerchantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_protobuf_merchant_merchant_proto_enumTypes[0].Descriptor()
}

func (MerchantStatus) Type() protoreflect.EnumType {
	return &file_contracts_protobuf_merchant_merchant_proto_enumTypes[0]
}

func (x MerchantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerchantStatus.Descriptor instead.
func (MerchantStatus) EnumDescriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{0}
}

type MerchantResponseData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BusinessName    string                 `protobuf:"bytes,2,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	FirstName       string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	BusinessEmail   string                 `protobuf:"bytes,5,opt,name=business_email,json=businessEmail,proto3" json:"business_email,omitempty"`
	BusinessPhone   string                 `protobuf:"bytes,6,opt,name=business_phone,json=businessPhone,proto3" json:"business_phone,omitempty"`
	PanCardNumber   string                 `protobuf:"bytes,7,opt,name=pan_card_number,json=panCardNumber,proto3" json:"pan_card_number,omitempty"`
	Status          MerchantStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=merchant.v1.MerchantStatus" json:"status,omitempty"`
	RejectionReason string                 `protobuf:"bytes,9,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MerchantResponseData) Reset() {
	*x = MerchantResponseData{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponseData) ProtoMessage() {}

func (x *MerchantResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponseData.ProtoReflect.Descriptor instead.
func (*MerchantResponseData) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantResponseData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantResponseData) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *MerchantResponseData) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MerchantResponseData) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MerchantResponseData) GetBusinessEmail() string {
	if x != nil {
		return x.BusinessEmail
	}
	return ""
}

func (x *MerchantResponseData) GetBusinessPhone() string {
	if x != nil {
		return x.BusinessPhone
	}
	return ""
}

func (x *MerchantResponseData) GetPanCardNumber() string {
	if x != nil {
		return x.PanCardNumber
	}
	return ""
}

func (x *MerchantResponseData) GetStatus() MerchantStatus {
	if x != nil {
		return x.Status
	}
	return MerchantStatus_PENDING
}

func (x *MerchantResponseData) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *MerchantResponseData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MerchantResponseData) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MerchantResponseData) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GetMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Pure merchant UUID lookup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *GetMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantResponseData  `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantResponse) GetMerchant() *MerchantResponseData {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type UpdateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BusinessName  string                 `protobuf:"bytes,2,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessPhone string                 `protobuf:"bytes,3,opt,name=business_phone,json=businessPhone,proto3" json:"business_phone,omitempty"`
	PanCardNumber string                 `protobuf:"bytes,4,opt,name=pan_card_number,json=panCardNumber,proto3" json:"pan_card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantRequest) Reset() {
	*x = UpdateMerchantRequest{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantRequest) ProtoMessage() {}

func (x *UpdateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMerchantRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *UpdateMerchantRequest) GetBusinessPhone() string {
	if x != nil {
		return x.BusinessPhone
	}
	return ""
}

func (x *UpdateMerchantRequest) GetPanCardNumber() string {
	if x != nil {
		return x.PanCardNumber
	}
	return ""
}

type UpdateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantResponseData  `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantResponse) Reset() {
	*x = UpdateMerchantResponse{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantResponse) ProtoMessage() {}

func (x *UpdateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantResponse.ProtoReflect.Descriptor instead.
func (*UpdateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMerchantResponse) GetMerchant() *MerchantResponseData {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type CreateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	BusinessEmail string                 `protobuf:"bytes,4,opt,name=business_email,json=businessEmail,proto3" json:"business_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantRequest) Reset() {
	*x = CreateMerchantRequest{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantRequest) ProtoMessage() {}

func (x *CreateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateMerchantRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateMerchantRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateMerchantRequest) GetBusinessEmail() string {
	if x != nil {
		return x.BusinessEmail
	}
	return ""
}

type CreateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantResponseData  `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantResponse) Reset() {
	*x = CreateMerchantResponse{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantResponse) ProtoMessage() {}

func (x *CreateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantResponse.ProtoReflect.Descriptor instead.
func (*CreateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMerchantResponse) GetMerchant() *MerchantResponseData {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type ListMerchantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        *MerchantStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=merchant.v1.MerchantStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsRequest) Reset() {
	*x = ListMerchantsRequest{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsRequest) ProtoMessage() {}

func (x *ListMerchantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *ListMerchantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMerchantsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMerchantsRequest) GetStatus() MerchantStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return MerchantStatus_PENDING
}

type ListMerchantsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Merchants     []*MerchantResponseData `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResponse) Reset() {
	*x = ListMerchantsResponse{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResponse) ProtoMessage() {}

func (x *ListMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *ListMerchantsResponse) GetMerchants() []*MerchantResponseData {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *ListMerchantsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateMerchantStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          MerchantStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=merchant.v1.MerchantStatus" json:"status,omitempty"`
	RejectionReason string                 `protobuf:"bytes,3,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateMerchantStatusRequest) Reset() {
	*x = UpdateMerchantStatusRequest{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantStatusRequest) ProtoMessage() {}

func (x *UpdateMerchantStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantStatusRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMerchantStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMerchantStatusRequest) GetStatus() MerchantStatus {
	if x != nil {
		return x.Status
	}
	return MerchantStatus_PENDING
}

func (x *UpdateMerchantStatusRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type UpdateMerchantStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Merchant       *MerchantResponseData  `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	PreviousStatus MerchantStatus         `protobuf:"varint,2,opt,name=previous_status,json=previousStatus,proto3,enum=merchant.v1.MerchantStatus" json:"previous_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMerchantStatusResponse) Reset() {
	*x = UpdateMerchantStatusResponse{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantStatusResponse) ProtoMessage() {}

func (x *UpdateMerchantStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateMerchantStatusResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMerchantStatusResponse) GetMerchant() *MerchantResponseData {
	if x != nil {
		return x.Merchant
	}
	return nil
}

func (x *UpdateMerchantStatusResponse) GetPreviousStatus() MerchantStatus {
	if x != nil {
		return x.PreviousStatus
	}
	return MerchantStatus_PENDING
}

type DeleteMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMerchantRequest) Reset() {
	*x = DeleteMerchantRequest{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantRequest) ProtoMessage() {}

func (x *DeleteMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantRequest.ProtoReflect.Descriptor instead.
func (*DeleteMerchantRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMerchantResponse) Reset() {
	*x = DeleteMerchantResponse{}
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantResponse) ProtoMessage() {}

func (x *DeleteMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_merchant_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantResponse.ProtoReflect.Descriptor instead.
func (*DeleteMerchantResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMerchantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_contracts_protobuf_merchant_merchant_proto protoreflect.FileDescriptor

const file_contracts_protobuf_merchant_merchant_proto_rawDesc = "" +
	"\n" +
	"*contracts/protobuf/merchant/merchant.proto\x12\vmerchant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x04\n" +
	"\x14MerchantResponseData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rbusiness_name\x18\x02 \x01(\tR\fbusinessName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12%\n" +
	"\x0ebusiness_email\x18\x05 \x01(\tR\rbusinessEmail\x12%\n" +
	"\x0ebusiness_phone\x18\x06 \x01(\tR\rbusinessPhone\x12&\n" +
	"\x0fpan_card_number\x18\a \x01(\tR\rpanCardNumber\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x1b.merchant.v1.MerchantStatusR\x06status\x12)\n" +
	"\x10rejection_reason\x18\t \x01(\tR\x0frejectionReason\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"$\n" +
	"\x12GetMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x13GetMerchantResponse\x12=\n" +
	"\bmerchant\x18\x01 \x01(\v2!.merchant.v1.MerchantResponseDataR\bmerchant\"\x9b\x01\n" +
	"\x15UpdateMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rbusiness_name\x18\x02 \x01(\tR\fbusinessName\x12%\n" +
	"\x0ebusiness_phone\x18\x03 \x01(\tR\rbusinessPhone\x12&\n" +
	"\x0fpan_card_number\x18\x04 \x01(\tR\rpanCardNumber\"W\n" +
	"\x16UpdateMerchantResponse\x12=\n" +
	"\bmerchant\x18\x01 \x01(\v2!.merchant.v1.MerchantResponseDataR\bmerchant\"\x8a\x01\n" +
	"\x15CreateMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12%\n" +
	"\x0ebusiness_email\x18\x04 \x01(\tR\rbusinessEmail\"W\n" +
	"\x16CreateMerchantResponse\x12=\n" +
	"\bmerchant\x18\x01 \x01(\v2!.merchant.v1.MerchantResponseDataR\bmerchant\"\x89\x01\n" +
	"\x14ListMerchantsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.merchant.v1.MerchantStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"n\n" +
	"\x15ListMerchantsResponse\x12?\n" +
	"\tmerchants\x18\x01 \x03(\v2!.merchant.v1.MerchantResponseDataR\tmerchants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8d\x01\n" +
	"\x1bUpdateMerchantStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.merchant.v1.MerchantStatusR\x06status\x12)\n" +
	"\x10rejection_reason\x18\x03 \x01(\tR\x0frejectionReason\"\xa3\x01\n" +
	"\x1cUpdateMerchantStatusResponse\x12=\n" +
	"\bmerchant\x18\x01 \x01(\v2!.merchant.v1.MerchantResponseDataR\bmerchant\x12D\n" +
	"\x0fprevious_status\x18\x02 \x01(\x0e2\x1b.merchant.v1.MerchantStatusR\x0epreviousStatus\"'\n" +
	"\x15DeleteMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteMerchantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*H\n" +
	"\x0eMerchantStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x032\xb9\x04\n" +
	"\x0fMerchantService\x12P\n" +
	"\vGetMerchant\x12\x1f.merchant.v1.GetMerchantRequest\x1a .merchant.v1.GetMerchantResponse\x12Y\n" +
	"\x0eUpdateMerchant\x12\".merchant.v1.UpdateMerchantRequest\x1a#.merchant.v1.UpdateMerchantResponse\x12Y\n" +
	"\x0eCreateMerchant\x12\".merchant.v1.CreateMerchantRequest\x1a#.merchant.v1.CreateMerchantResponse\x12V\n" +
	"\rListMerchants\x12!.merchant.v1.ListMerchantsRequest\x1a\".merchant.v1.ListMerchantsResponse\x12k\n" +
	"\x14UpdateMerchantStatus\x12(.merchant.v1.UpdateMerchantStatusRequest\x1a).merchant.v1.UpdateMerchantStatusResponse\x12Y\n" +
	"\x0eDeleteMerchant\x12\".merchant.v1.DeleteMerchantRequest\x1a#.merchant.v1.DeleteMerchantResponseBLZJgithub.com/marees-godev/GoCart-Server/contracts/protobuf/merchant;merchantb\x06proto3"

var (
	file_contracts_protobuf_merchant_merchant_proto_rawDescOnce sync.Once
	file_contracts_protobuf_merchant_merchant_proto_rawDescData []byte
)

func file_contracts_protobuf_merchant_merchant_proto_rawDescGZIP() []byte {
	file_contracts_protobuf_merchant_merchant_proto_rawDescOnce.Do(func() {
		file_contracts_protobuf_merchant_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_protobuf_merchant_merchant_proto_rawDesc), len(file_contracts_protobuf_merchant_merchant_proto_rawDesc)))
	})
	return file_contracts_protobuf_merchant_merchant_proto_rawDescData
}

var file_contracts_protobuf_merchant_merchant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_protobuf_merchant_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_contracts_protobuf_merchant_merchant_proto_goTypes = []any{
	(MerchantStatus)(0),                  // 0: merchant.v1.MerchantStatus
	(*MerchantResponseData)(nil),         // 1: merchant.v1.MerchantResponseData
	(*GetMerchantRequest)(nil),           // 2: merchant.v1.GetMerchantRequest
	(*GetMerchantResponse)(nil),          // 3: merchant.v1.GetMerchantResponse
	(*UpdateMerchantRequest)(nil),        // 4: merchant.v1.UpdateMerchantRequest
	(*UpdateMerchantResponse)(nil),       // 5: merchant.v1.UpdateMerchantResponse
	(*CreateMerchantRequest)(nil),        // 6: merchant.v1.CreateMerchantRequest
	(*CreateMerchantResponse)(nil),       // 7: merchant.v1.CreateMerchantResponse
	(*ListMerchantsRequest)(nil),         // 8: merchant.v1.ListMerchantsRequest
	(*ListMerchantsResponse)(nil),        // 9: merchant.v1.ListMerchantsResponse
	(*UpdateMerchantStatusRequest)(nil),  // 10: merchant.v1.UpdateMerchantStatusRequest
	(*UpdateMerchantStatusResponse)(nil), // 11: merchant.v1.UpdateMerchantStatusResponse
	(*DeleteMerchantRequest)(nil),        // 12: merchant.v1.DeleteMerchantRequest
	(*DeleteMerchantResponse)(nil),       // 13: merchant.v1.DeleteMerchantResponse
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
}
var file_contracts_protobuf_merchant_merchant_proto_depIdxs = []int32{
	0,  // 0: merchant.v1.MerchantResponseData.status:type_name -> merchant.v1.MerchantStatus
	14, // 1: merchant.v1.MerchantResponseData.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: merchant.v1.MerchantResponseData.updated_at:type_name -> google.protobuf.Timestamp
	14, // 3: merchant.v1.MerchantResponseData.deleted_at:type_name -> google.protobuf.Timestamp
	1,  // 4: merchant.v1.GetMerchantResponse.merchant:type_name -> merchant.v1.MerchantResponseData
	1,  // 5: merchant.v1.UpdateMerchantResponse.merchant:type_name -> merchant.v1.MerchantResponseData
	1,  // 6: merchant.v1.CreateMerchantResponse.merchant:type_name -> merchant.v1.MerchantResponseData
	0,  // 7: merchant.v1.ListMerchantsRequest.status:type_name -> merchant.v1.MerchantStatus
	1,  // 8: merchant.v1.ListMerchantsResponse.merchants:type_name -> merchant.v1.MerchantResponseData
	0,  // 9: merchant.v1.UpdateMerchantStatusRequest.status:type_name -> merchant.v1.MerchantStatus
	1,  // 10: merchant.v1.UpdateMerchantStatusResponse.merchant:type_name -> merchant.v1.MerchantResponseData
	0,  // 11: merchant.v1.UpdateMerchantStatusResponse.previous_status:type_name -> merchant.v1.MerchantStatus
	2,  // 12: merchant.v1.MerchantService.GetMerchant:input_type -> merchant.v1.GetMerchantRequest
	4,  // 13: merchant.v1.MerchantService.UpdateMerchant:input_type -> merchant.v1.UpdateMerchantRequest
	6,  // 14: merchant.v1.MerchantService.CreateMerchant:input_type -> merchant.v1.CreateMerchantRequest
	8,  // 15: merchant.v1.MerchantService.ListMerchants:input_type -> merchant.v1.ListMerchantsRequest
	10, // 16: merchant.v1.MerchantService.UpdateMerchantStatus:input_type -> merchant.v1.UpdateMerchantStatusRequest
	12, // 17: merchant.v1.MerchantService.DeleteMerchant:input_type -> merchant.v1.DeleteMerchantRequest
	3,  // 18: merchant.v1.MerchantService.GetMerchant:output_type -> merchant.v1.GetMerchantResponse
	5,  // 19: merchant.v1.MerchantService.UpdateMerchant:output_type -> merchant.v1.UpdateMerchantResponse
	7,  // 20: merchant.v1.MerchantService.CreateMerchant:output_type -> merchant.v1.CreateMerchantResponse
	9,  // 21: merchant.v1.MerchantService.ListMerchants:output_type -> merchant.v1.ListMerchantsResponse
	11, // 22: merchant.v1.MerchantService.UpdateMerchantStatus:output_type -> merchant.v1.UpdateMerchantStatusResponse
	13, // 23: merchant.v1.MerchantService.DeleteMerchant:output_type -> merchant.v1.DeleteMerchantResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_contracts_protobuf_merchant_merchant_proto_init() }
func file_contracts_protobuf_merchant_merchant_proto_init() {
	if File_contracts_protobuf_merchant_merchant_proto != nil {
		return
	}
	file_contracts_protobuf_merchant_merchant_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_protobuf_merchant_merchant_proto_rawDesc), len(file_contracts_protobuf_merchant_merchant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_protobuf_merchant_merchant_proto_goTypes,
		DependencyIndexes: file_contracts_protobuf_merchant_merchant_proto_depIdxs,
		EnumInfos:         file_contracts_protobuf_merchant_merchant_proto_enumTypes,
		MessageInfos:      file_contracts_protobuf_merchant_merchant_proto_msgTypes,
	}.Build()
	File_contracts_protobuf_merchant_merchant_proto = out.File
	file_contracts_protobuf_merchant_merchant_proto_goTypes = nil
	file_contracts_protobuf_merchant_merchant_proto_depIdxs = nil
}
