// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.5
// source: contracts/protobuf/cart/cart.proto

package cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,4,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *CartItem) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CartItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{1}
}

func (x *Cart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cart) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Cart) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type AddCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,4,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemRequest) Reset() {
	*x = AddCartItemRequest{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemRequest) ProtoMessage() {}

func (x *AddCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemRequest.ProtoReflect.Descriptor instead.
func (*AddCartItemRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{4}
}

func (x *AddCartItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCartItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddCartItemRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *AddCartItemRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *AddCartItemRequest) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *AddCartItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemResponse) Reset() {
	*x = AddCartItemResponse{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemResponse) ProtoMessage() {}

func (x *AddCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemResponse.ProtoReflect.Descriptor instead.
func (*AddCartItemResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{5}
}

func (x *AddCartItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type UpdateCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemRequest) Reset() {
	*x = UpdateCartItemRequest{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemRequest) ProtoMessage() {}

func (x *UpdateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCartItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCartItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateCartItemRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *UpdateCartItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemResponse) Reset() {
	*x = UpdateCartItemResponse{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemResponse) ProtoMessage() {}

func (x *UpdateCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateCartItemResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCartItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type RemoveCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartItemRequest) Reset() {
	*x = RemoveCartItemRequest{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartItemRequest) ProtoMessage() {}

func (x *RemoveCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveCartItemRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveCartItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveCartItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RemoveCartItemRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

type RemoveCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartItemResponse) Reset() {
	*x = RemoveCartItemResponse{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartItemResponse) ProtoMessage() {}

func (x *RemoveCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveCartItemResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveCartItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{10}
}

func (x *ClearCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Cart          *Cart                  `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{11}
}

func (x *ClearCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type ValidateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCartRequest) Reset() {
	*x = ValidateCartRequest{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCartRequest) ProtoMessage() {}

func (x *ValidateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCartRequest.ProtoReflect.Descriptor instead.
func (*ValidateCartRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{13}
}

func (x *ValidationError) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type StoreOrderGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreOrderGroup) Reset() {
	*x = StoreOrderGroup{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOrderGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOrderGroup) ProtoMessage() {}

func (x *StoreOrderGroup) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOrderGroup.ProtoReflect.Descriptor instead.
func (*StoreOrderGroup) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{14}
}

func (x *StoreOrderGroup) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *StoreOrderGroup) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StoreOrderGroup) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

type ValidateCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Cart          *Cart                  `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	StoreGroups   []*StoreOrderGroup     `protobuf:"bytes,4,rep,name=store_groups,json=storeGroups,proto3" json:"store_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCartResponse) Reset() {
	*x = ValidateCartResponse{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCartResponse) ProtoMessage() {}

func (x *ValidateCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCartResponse.ProtoReflect.Descriptor instead.
func (*ValidateCartResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateCartResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *ValidateCartResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateCartResponse) GetStoreGroups() []*StoreOrderGroup {
	if x != nil {
		return x.StoreGroups
	}
	return nil
}

type PrepareCheckoutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,2,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrepareCheckoutRequest) Reset() {
	*x = PrepareCheckoutRequest{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareCheckoutRequest) ProtoMessage() {}

func (x *PrepareCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareCheckoutRequest.ProtoReflect.Descriptor instead.
func (*PrepareCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{16}
}

func (x *PrepareCheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PrepareCheckoutRequest) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

type StoreOrderPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentOrderId   string                 `protobuf:"bytes,1,opt,name=parent_order_id,json=parentOrderId,proto3" json:"parent_order_id,omitempty"`
	StoreId         string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items           []*CartItem            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal        float64                `protobuf:"fixed64,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,7,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreOrderPayload) Reset() {
	*x = StoreOrderPayload{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreOrderPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOrderPayload) ProtoMessage() {}

func (x *StoreOrderPayload) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOrderPayload.ProtoReflect.Descriptor instead.
func (*StoreOrderPayload) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{17}
}

func (x *StoreOrderPayload) GetParentOrderId() string {
	if x != nil {
		return x.ParentOrderId
	}
	return ""
}

func (x *StoreOrderPayload) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *StoreOrderPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreOrderPayload) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StoreOrderPayload) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *StoreOrderPayload) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *StoreOrderPayload) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

type PrepareCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ParentOrderId string                 `protobuf:"bytes,2,opt,name=parent_order_id,json=parentOrderId,proto3" json:"parent_order_id,omitempty"`
	Orders        []*StoreOrderPayload   `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareCheckoutResponse) Reset() {
	*x = PrepareCheckoutResponse{}
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareCheckoutResponse) ProtoMessage() {}

func (x *PrepareCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_cart_cart_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareCheckoutResponse.ProtoReflect.Descriptor instead.
func (*PrepareCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_cart_cart_proto_rawDescGZIP(), []int{18}
}

func (x *PrepareCheckoutResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *PrepareCheckoutResponse) GetParentOrderId() string {
	if x != nil {
		return x.ParentOrderId
	}
	return ""
}

func (x *PrepareCheckoutResponse) GetOrders() []*StoreOrderPayload {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *PrepareCheckoutResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_contracts_protobuf_cart_cart_proto protoreflect.FileDescriptor

const file_contracts_protobuf_cart_cart_proto_rawDesc = "" +
	"\n" +
	"\"contracts/protobuf/cart/cart.proto\x12\x0egocart.cart.v1\"\xae\x01\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x19\n" +
	"\bstore_id\x18\x04 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\"\xa1\x01\n" +
	"\x04Cart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12.\n" +
	"\x05items\x18\x03 \x03(\v2\x18.gocart.cart.v1.CartItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x0fGetCartResponse\x12(\n" +
	"\x04cart\x18\x01 \x01(\v2\x14.gocart.cart.v1.CartR\x04cart\"\xc1\x01\n" +
	"\x12AddCartItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x19\n" +
	"\bstore_id\x18\x04 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\"?\n" +
	"\x13AddCartItemResponse\x12(\n" +
	"\x04cart\x18\x01 \x01(\v2\x14.gocart.cart.v1.CartR\x04cart\"\x8a\x01\n" +
	"\x15UpdateCartItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"B\n" +
	"\x16UpdateCartItemResponse\x12(\n" +
	"\x04cart\x18\x01 \x01(\v2\x14.gocart.cart.v1.CartR\x04cart\"n\n" +
	"\x15RemoveCartItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\"B\n" +
	"\x16RemoveCartItemResponse\x12(\n" +
	"\x04cart\x18\x01 \x01(\v2\x14.gocart.cart.v1.CartR\x04cart\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x11ClearCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x04cart\x18\x02 \x01(\v2\x14.gocart.cart.v1.CartR\x04cart\".\n" +
	"\x13ValidateCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x0fValidationError\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"x\n" +
	"\x0fStoreOrderGroup\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.gocart.cart.v1.CartItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\x01R\bsubtotal\"\xd8\x01\n" +
	"\x14ValidateCartResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12(\n" +
	"\x04cart\x18\x02 \x01(\v2\x14.gocart.cart.v1.CartR\x04cart\x127\n" +
	"\x06errors\x18\x03 \x03(\v2\x1f.gocart.cart.v1.ValidationErrorR\x06errors\x12B\n" +
	"\fstore_groups\x18\x04 \x03(\v2\x1f.gocart.cart.v1.StoreOrderGroupR\vstoreGroups\"\\\n" +
	"\x16PrepareCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10shipping_address\x18\x02 \x01(\tR\x0fshippingAddress\"\x89\x02\n" +
	"\x11StoreOrderPayload\x12&\n" +
	"\x0fparent_order_id\x18\x01 \x01(\tR\rparentOrderId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12.\n" +
	"\x05items\x18\x04 \x03(\v2\x18.gocart.cart.v1.CartItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\x01R\bsubtotal\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x12)\n" +
	"\x10shipping_address\x18\a \x01(\tR\x0fshippingAddress\"\xd0\x01\n" +
	"\x17PrepareCheckoutResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12&\n" +
	"\x0fparent_order_id\x18\x02 \x01(\tR\rparentOrderId\x129\n" +
	"\x06orders\x18\x03 \x03(\v2!.gocart.cart.v1.StoreOrderPayloadR\x06orders\x127\n" +
	"\x06errors\x18\x04 \x03(\v2\x1f.gocart.cart.v1.ValidationErrorR\x06errors2\x84\x05\n" +
	"\vCartService\x12J\n" +
	"\aGetCart\x12\x1e.gocart.cart.v1.GetCartRequest\x1a\x1f.gocart.cart.v1.GetCartResponse\x12V\n" +
	"\vAddCartItem\x12\".gocart.cart.v1.AddCartItemRequest\x1a#.gocart.cart.v1.AddCartItemResponse\x12_\n" +
	"\x0eUpdateCartItem\x12%.gocart.cart.v1.UpdateCartItemRequest\x1a&.gocart.cart.v1.UpdateCartItemResponse\x12_\n" +
	"\x0eRemoveCartItem\x12%.gocart.cart.v1.RemoveCartItemRequest\x1a&.gocart.cart.v1.RemoveCartItemResponse\x12P\n" +
	"\tClearCart\x12 .gocart.cart.v1.ClearCartRequest\x1a!.gocart.cart.v1.ClearCartResponse\x12Y\n" +
	"\fValidateCart\x12#.gocart.cart.v1.ValidateCartRequest\x1a$.gocart.cart.v1.ValidateCartResponse\x12b\n" +
	"\x0fPrepareCheckout\x12&.gocart.cart.v1.PrepareCheckoutRequest\x1a'.gocart.cart.v1.PrepareCheckoutResponseBDZBgithub.com/marees-godev/GoCart-Server/contracts/protobuf/cart;cartb\x06proto3"

var (
	file_contracts_protobuf_cart_cart_proto_rawDescOnce sync.Once
	file_contracts_protobuf_cart_cart_proto_rawDescData []byte
)

func file_contracts_protobuf_cart_cart_proto_rawDescGZIP() []byte {
	file_contracts_protobuf_cart_cart_proto_rawDescOnce.Do(func() {
		file_contracts_protobuf_cart_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_protobuf_cart_cart_proto_rawDesc), len(file_contracts_protobuf_cart_cart_proto_rawDesc)))
	})
	return file_contracts_protobuf_cart_cart_proto_rawDescData
}

var file_contracts_protobuf_cart_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_contracts_protobuf_cart_cart_proto_goTypes = []any{
	(*CartItem)(nil),                // 0: gocart.cart.v1.CartItem
	(*Cart)(nil),                    // 1: gocart.cart.v1.Cart
	(*GetCartRequest)(nil),          // 2: gocart.cart.v1.GetCartRequest
	(*GetCartResponse)(nil),         // 3: gocart.cart.v1.GetCartResponse
	(*AddCartItemRequest)(nil),      // 4: gocart.cart.v1.AddCartItemRequest
	(*AddCartItemResponse)(nil),     // 5: gocart.cart.v1.AddCartItemResponse
	(*UpdateCartItemRequest)(nil),   // 6: gocart.cart.v1.UpdateCartItemRequest
	(*UpdateCartItemResponse)(nil),  // 7: gocart.cart.v1.UpdateCartItemResponse
	(*RemoveCartItemRequest)(nil),   // 8: gocart.cart.v1.RemoveCartItemRequest
	(*RemoveCartItemResponse)(nil),  // 9: gocart.cart.v1.RemoveCartItemResponse
	(*ClearCartRequest)(nil),        // 10: gocart.cart.v1.ClearCartRequest
	(*ClearCartResponse)(nil),       // 11: gocart.cart.v1.ClearCartResponse
	(*ValidateCartRequest)(nil),     // 12: gocart.cart.v1.ValidateCartRequest
	(*ValidationError)(nil),         // 13: gocart.cart.v1.ValidationError
	(*StoreOrderGroup)(nil),         // 14: gocart.cart.v1.StoreOrderGroup
	(*ValidateCartResponse)(nil),    // 15: gocart.cart.v1.ValidateCartResponse
	(*PrepareCheckoutRequest)(nil),  // 16: gocart.cart.v1.PrepareCheckoutRequest
	(*StoreOrderPayload)(nil),       // 17: gocart.cart.v1.StoreOrderPayload
	(*PrepareCheckoutResponse)(nil), // 18: gocart.cart.v1.PrepareCheckoutResponse
}
var file_contracts_protobuf_cart_cart_proto_depIdxs = []int32{
	0,  // 0: gocart.cart.v1.Cart.items:type_name -> gocart.cart.v1.CartItem
	1,  // 1: gocart.cart.v1.GetCartResponse.cart:type_name -> gocart.cart.v1.Cart
	1,  // 2: gocart.cart.v1.AddCartItemResponse.cart:type_name -> gocart.cart.v1.Cart
	1,  // 3: gocart.cart.v1.UpdateCartItemResponse.cart:type_name -> gocart.cart.v1.Cart
	1,  // 4: gocart.cart.v1.RemoveCartItemResponse.cart:type_name -> gocart.cart.v1.Cart
	1,  // 5: gocart.cart.v1.ClearCartResponse.cart:type_name -> gocart.cart.v1.Cart
	0,  // 6: gocart.cart.v1.StoreOrderGroup.items:type_name -> gocart.cart.v1.CartItem
	1,  // 7: gocart.cart.v1.ValidateCartResponse.cart:type_name -> gocart.cart.v1.Cart
	13, // 8: gocart.cart.v1.ValidateCartResponse.errors:type_name -> gocart.cart.v1.ValidationError
	14, // 9: gocart.cart.v1.ValidateCartResponse.store_groups:type_name -> gocart.cart.v1.StoreOrderGroup
	0,  // 10: gocart.cart.v1.StoreOrderPayload.items:type_name -> gocart.cart.v1.CartItem
	17, // 11: gocart.cart.v1.PrepareCheckoutResponse.orders:type_name -> gocart.cart.v1.StoreOrderPayload
	13, // 12: gocart.cart.v1.PrepareCheckoutResponse.errors:type_name -> gocart.cart.v1.ValidationError
	2,  // 13: gocart.cart.v1.CartService.GetCart:input_type -> gocart.cart.v1.GetCartRequest
	4,  // 14: gocart.cart.v1.CartService.AddCartItem:input_type -> gocart.cart.v1.AddCartItemRequest
	6,  // 15: gocart.cart.v1.CartService.UpdateCartItem:input_type -> gocart.cart.v1.UpdateCartItemRequest
	8,  // 16: gocart.cart.v1.CartService.RemoveCartItem:input_type -> gocart.cart.v1.RemoveCartItemRequest
	10, // 17: gocart.cart.v1.CartService.ClearCart:input_type -> gocart.cart.v1.ClearCartRequest
	12, // 18: gocart.cart.v1.CartService.ValidateCart:input_type -> gocart.cart.v1.ValidateCartRequest
	16, // 19: gocart.cart.v1.CartService.PrepareCheckout:input_type -> gocart.cart.v1.PrepareCheckoutRequest
	3,  // 20: gocart.cart.v1.CartService.GetCart:output_type -> gocart.cart.v1.GetCartResponse
	5,  // 21: gocart.cart.v1.CartService.AddCartItem:output_type -> gocart.cart.v1.AddCartItemResponse
	7,  // 22: gocart.cart.v1.CartService.UpdateCartItem:output_type -> gocart.cart.v1.UpdateCartItemResponse
	9,  // 23: gocart.cart.v1.CartService.RemoveCartItem:output_type -> gocart.cart.v1.RemoveCartItemResponse
	11, // 24: gocart.cart.v1.CartService.ClearCart:output_type -> gocart.cart.v1.ClearCartResponse
	15, // 25: gocart.cart.v1.CartService.ValidateCart:output_type -> gocart.cart.v1.ValidateCartResponse
	18, // 26: gocart.cart.v1.CartService.PrepareCheckout:output_type -> gocart.cart.v1.PrepareCheckoutResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_contracts_protobuf_cart_cart_proto_init() }
func file_contracts_protobuf_cart_cart_proto_init() {
	if File_contracts_protobuf_cart_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_protobuf_cart_cart_proto_rawDesc), len(file_contracts_protobuf_cart_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_protobuf_cart_cart_proto_goTypes,
		DependencyIndexes: file_contracts_protobuf_cart_cart_proto_depIdxs,
		MessageInfos:      file_contracts_protobuf_cart_cart_proto_msgTypes,
	}.Build()
	File_contracts_protobuf_cart_cart_proto = out.File
	file_contracts_protobuf_cart_cart_proto_goTypes = nil
	file_contracts_protobuf_cart_cart_proto_depIdxs = nil
}
