ALTER TYPE product_status ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE product_status ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE product_status ADD VALUE IF NOT EXISTS 'PUBLISHED';
ALTER TYPE product_status ADD VALUE IF NOT EXISTS 'UNPUBLISHED';
ALTER TYPE product_status ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE product_status ADD VALUE IF NOT EXISTS 'DELETED';
ALTER TABLE products ALTER COLUMN status SET DEFAULT 'DRAFT';
