// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: contracts/protobuf/category/category.proto

package category

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ParentCategoryId string                 `protobuf:"bytes,8,opt,name=parent_category_id,json=parentCategoryId,proto3" json:"parent_category_id,omitempty"`
	IsActive         bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Category) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Category) GetParentCategoryId() string {
	if x != nil {
		return x.ParentCategoryId
	}
	return ""
}

func (x *Category) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateCategoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentCategoryId string                 `protobuf:"bytes,5,opt,name=parent_category_id,json=parentCategoryId,proto3" json:"parent_category_id,omitempty"`
	IsActive         *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCategoryRequest) GetParentCategoryId() string {
	if x != nil {
		return x.ParentCategoryId
	}
	return ""
}

func (x *CreateCategoryRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{3}
}

func (x *GetCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResponse) Reset() {
	*x = GetCategoryResponse{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResponse) ProtoMessage() {}

func (x *GetCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{4}
}

func (x *GetCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ListCategoriesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Limit            int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ParentCategoryId string                 `protobuf:"bytes,3,opt,name=parent_category_id,json=parentCategoryId,proto3" json:"parent_category_id,omitempty"`
	RootOnly         bool                   `protobuf:"varint,4,opt,name=root_only,json=rootOnly,proto3" json:"root_only,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{5}
}

func (x *ListCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCategoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCategoriesRequest) GetParentCategoryId() string {
	if x != nil {
		return x.ParentCategoryId
	}
	return ""
}

func (x *ListCategoriesRequest) GetRootOnly() bool {
	if x != nil {
		return x.RootOnly
	}
	return false
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{6}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListCategoriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetChildCategoriesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParentCategoryId string                 `protobuf:"bytes,1,opt,name=parent_category_id,json=parentCategoryId,proto3" json:"parent_category_id,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetChildCategoriesRequest) Reset() {
	*x = GetChildCategoriesRequest{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChildCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildCategoriesRequest) ProtoMessage() {}

func (x *GetChildCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetChildCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{7}
}

func (x *GetChildCategoriesRequest) GetParentCategoryId() string {
	if x != nil {
		return x.ParentCategoryId
	}
	return ""
}

func (x *GetChildCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChildCategoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetChildCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChildCategoriesResponse) Reset() {
	*x = GetChildCategoriesResponse{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChildCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildCategoriesResponse) ProtoMessage() {}

func (x *GetChildCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetChildCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{8}
}

func (x *GetChildCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetChildCategoriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateCategoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentCategoryId string                 `protobuf:"bytes,5,opt,name=parent_category_id,json=parentCategoryId,proto3" json:"parent_category_id,omitempty"`
	IsActive         *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCategoryRequest) GetParentCategoryId() string {
	if x != nil {
		return x.ParentCategoryId
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateCategoryForAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCategoryForAssignmentRequest) Reset() {
	*x = ValidateCategoryForAssignmentRequest{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCategoryForAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCategoryForAssignmentRequest) ProtoMessage() {}

func (x *ValidateCategoryForAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCategoryForAssignmentRequest.ProtoReflect.Descriptor instead.
func (*ValidateCategoryForAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateCategoryForAssignmentRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type ValidateCategoryForAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Category      *Category              `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCategoryForAssignmentResponse) Reset() {
	*x = ValidateCategoryForAssignmentResponse{}
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCategoryForAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCategoryForAssignmentResponse) ProtoMessage() {}

func (x *ValidateCategoryForAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_protobuf_category_category_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCategoryForAssignmentResponse.ProtoReflect.Descriptor instead.
func (*ValidateCategoryForAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_contracts_protobuf_category_category_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateCategoryForAssignmentResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateCategoryForAssignmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateCategoryForAssignmentResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_contracts_protobuf_category_category_proto protoreflect.FileDescriptor

const file_contracts_protobuf_category_category_proto_rawDesc = "" +
	"\n" +
	"*contracts/protobuf/category/category.proto\x12\x12gocart.category.v1\"\xd9\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12,\n" +
	"\x12parent_category_id\x18\b \x01(\tR\x10parentCategoryId\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\"\xab\x01\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12,\n" +
	"\x12parent_category_id\x18\x05 \x01(\tR\x10parentCategoryId\x12 \n" +
	"\tis_active\x18\x06 \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\"R\n" +
	"\x16CreateCategoryResponse\x128\n" +
	"\bcategory\x18\x01 \x01(\v2\x1c.gocart.category.v1.CategoryR\bcategory\"$\n" +
	"\x12GetCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x13GetCategoryResponse\x128\n" +
	"\bcategory\x18\x01 \x01(\v2\x1c.gocart.category.v1.CategoryR\bcategory\"\x90\x01\n" +
	"\x15ListCategoriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12,\n" +
	"\x12parent_category_id\x18\x03 \x01(\tR\x10parentCategoryId\x12\x1b\n" +
	"\troot_only\x18\x04 \x01(\bR\brootOnly\"l\n" +
	"\x16ListCategoriesResponse\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.gocart.category.v1.CategoryR\n" +
	"categories\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"w\n" +
	"\x19GetChildCategoriesRequest\x12,\n" +
	"\x12parent_category_id\x18\x01 \x01(\tR\x10parentCategoryId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"p\n" +
	"\x1aGetChildCategoriesResponse\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.gocart.category.v1.CategoryR\n" +
	"categories\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xbb\x01\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12,\n" +
	"\x12parent_category_id\x18\x05 \x01(\tR\x10parentCategoryId\x12 \n" +
	"\tis_active\x18\x06 \x01(\bH\x00R\bisActive\x88\x01\x01B\f\n" +
	"\n" +
	"_is_active\"R\n" +
	"\x16UpdateCategoryResponse\x128\n" +
	"\bcategory\x18\x01 \x01(\v2\x1c.gocart.category.v1.CategoryR\bcategory\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DeleteCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"$ValidateCategoryForAssignmentRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"\x96\x01\n" +
	"%ValidateCategoryForAssignmentResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\bcategory\x18\x03 \x01(\v2\x1c.gocart.category.v1.CategoryR\bcategory2\xa1\x06\n" +
	"\x0fCategoryService\x12g\n" +
	"\x0eCreateCategory\x12).gocart.category.v1.CreateCategoryRequest\x1a*.gocart.category.v1.CreateCategoryResponse\x12^\n" +
	"\vGetCategory\x12&.gocart.category.v1.GetCategoryRequest\x1a'.gocart.category.v1.GetCategoryResponse\x12g\n" +
	"\x0eListCategories\x12).gocart.category.v1.ListCategoriesRequest\x1a*.gocart.category.v1.ListCategoriesResponse\x12s\n" +
	"\x12GetChildCategories\x12-.gocart.category.v1.GetChildCategoriesRequest\x1a..gocart.category.v1.GetChildCategoriesResponse\x12g\n" +
	"\x0eUpdateCategory\x12).gocart.category.v1.UpdateCategoryRequest\x1a*.gocart.category.v1.UpdateCategoryResponse\x12g\n" +
	"\x0eDeleteCategory\x12).gocart.category.v1.DeleteCategoryRequest\x1a*.gocart.category.v1.DeleteCategoryResponse\x12\x94\x01\n" +
	"\x1dValidateCategoryForAssignment\x128.gocart.category.v1.ValidateCategoryForAssignmentRequest\x1a9.gocart.category.v1.ValidateCategoryForAssignmentResponseBLZJgithub.com/marees-godev/GoCart-Server/contracts/protobuf/category;categoryb\x06proto3"

var (
	file_contracts_protobuf_category_category_proto_rawDescOnce sync.Once
	file_contracts_protobuf_category_category_proto_rawDescData []byte
)

func file_contracts_protobuf_category_category_proto_rawDescGZIP() []byte {
	file_contracts_protobuf_category_category_proto_rawDescOnce.Do(func() {
		file_contracts_protobuf_category_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_protobuf_category_category_proto_rawDesc), len(file_contracts_protobuf_category_category_proto_rawDesc)))
	})
	return file_contracts_protobuf_category_category_proto_rawDescData
}

var file_contracts_protobuf_category_category_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_contracts_protobuf_category_category_proto_goTypes = []any{
	(*Category)(nil),                              // 0: gocart.category.v1.Category
	(*CreateCategoryRequest)(nil),                 // 1: gocart.category.v1.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),                // 2: gocart.category.v1.CreateCategoryResponse
	(*GetCategoryRequest)(nil),                    // 3: gocart.category.v1.GetCategoryRequest
	(*GetCategoryResponse)(nil),                   // 4: gocart.category.v1.GetCategoryResponse
	(*ListCategoriesRequest)(nil),                 // 5: gocart.category.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),                // 6: gocart.category.v1.ListCategoriesResponse
	(*GetChildCategoriesRequest)(nil),             // 7: gocart.category.v1.GetChildCategoriesRequest
	(*GetChildCategoriesResponse)(nil),            // 8: gocart.category.v1.GetChildCategoriesResponse
	(*UpdateCategoryRequest)(nil),                 // 9: gocart.category.v1.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),                // 10: gocart.category.v1.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),                 // 11: gocart.category.v1.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),                // 12: gocart.category.v1.DeleteCategoryResponse
	(*ValidateCategoryForAssignmentRequest)(nil),  // 13: gocart.category.v1.ValidateCategoryForAssignmentRequest
	(*ValidateCategoryForAssignmentResponse)(nil), // 14: gocart.category.v1.ValidateCategoryForAssignmentResponse
}
var file_contracts_protobuf_category_category_proto_depIdxs = []int32{
	0,  // 0: gocart.category.v1.CreateCategoryResponse.category:type_name -> gocart.category.v1.Category
	0,  // 1: gocart.category.v1.GetCategoryResponse.category:type_name -> gocart.category.v1.Category
	0,  // 2: gocart.category.v1.ListCategoriesResponse.categories:type_name -> gocart.category.v1.Category
	0,  // 3: gocart.category.v1.GetChildCategoriesResponse.categories:type_name -> gocart.category.v1.Category
	0,  // 4: gocart.category.v1.UpdateCategoryResponse.category:type_name -> gocart.category.v1.Category
	0,  // 5: gocart.category.v1.ValidateCategoryForAssignmentResponse.category:type_name -> gocart.category.v1.Category
	1,  // 6: gocart.category.v1.CategoryService.CreateCategory:input_type -> gocart.category.v1.CreateCategoryRequest
	3,  // 7: gocart.category.v1.CategoryService.GetCategory:input_type -> gocart.category.v1.GetCategoryRequest
	5,  // 8: gocart.category.v1.CategoryService.ListCategories:input_type -> gocart.category.v1.ListCategoriesRequest
	7,  // 9: gocart.category.v1.CategoryService.GetChildCategories:input_type -> gocart.category.v1.GetChildCategoriesRequest
	9,  // 10: gocart.category.v1.CategoryService.UpdateCategory:input_type -> gocart.category.v1.UpdateCategoryRequest
	11, // 11: gocart.category.v1.CategoryService.DeleteCategory:input_type -> gocart.category.v1.DeleteCategoryRequest
	13, // 12: gocart.category.v1.CategoryService.ValidateCategoryForAssignment:input_type -> gocart.category.v1.ValidateCategoryForAssignmentRequest
	2,  // 13: gocart.category.v1.CategoryService.CreateCategory:output_type -> gocart.category.v1.CreateCategoryResponse
	4,  // 14: gocart.category.v1.CategoryService.GetCategory:output_type -> gocart.category.v1.GetCategoryResponse
	6,  // 15: gocart.category.v1.CategoryService.ListCategories:output_type -> gocart.category.v1.ListCategoriesResponse
	8,  // 16: gocart.category.v1.CategoryService.GetChildCategories:output_type -> gocart.category.v1.GetChildCategoriesResponse
	10, // 17: gocart.category.v1.CategoryService.UpdateCategory:output_type -> gocart.category.v1.UpdateCategoryResponse
	12, // 18: gocart.category.v1.CategoryService.DeleteCategory:output_type -> gocart.category.v1.DeleteCategoryResponse
	14, // 19: gocart.category.v1.CategoryService.ValidateCategoryForAssignment:output_type -> gocart.category.v1.ValidateCategoryForAssignmentResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_contracts_protobuf_category_category_proto_init() }
func file_contracts_protobuf_category_category_proto_init() {
	if File_contracts_protobuf_category_category_proto != nil {
		return
	}
	file_contracts_protobuf_category_category_proto_msgTypes[1].OneofWrappers = []any{}
	file_contracts_protobuf_category_category_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_protobuf_category_category_proto_rawDesc), len(file_contracts_protobuf_category_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_protobuf_category_category_proto_goTypes,
		DependencyIndexes: file_contracts_protobuf_category_category_proto_depIdxs,
		MessageInfos:      file_contracts_protobuf_category_category_proto_msgTypes,
	}.Build()
	File_contracts_protobuf_category_category_proto = out.File
	file_contracts_protobuf_category_category_proto_goTypes = nil
	file_contracts_protobuf_category_category_proto_depIdxs = nil
}
