syntax = "proto3";

package gocart.cart;

option go_package = "github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/grpc/pb/cartpb";

service CartService {
  rpc GetCart (GetCartRequest) returns (GetCartResponse);
  rpc AddToCart (AddToCartRequest) returns (AddToCartResponse);
}

message CartItem {
  string id = 1;
  string product_id = 2;
  int32 quantity = 3;
  double unit_price = 4;
}

message Cart {
  string id = 1;
  string user_id = 2;
  repeated CartItem items = 3;
  double total_amount = 4;
}

message GetCartRequest {
  string user_id = 1;
}

message GetCartResponse {
  Cart cart = 1;
}

message AddToCartRequest {
  string user_id = 1;
  string product_id = 2;
  int32 quantity = 3;
}

message AddToCartResponse {
  Cart cart = 1;
}
