syntax = "proto3";

package gocart.order;

option go_package = "github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/grpc/pb/orderpb";

service OrderService {
  rpc GetOrder (GetOrderRequest) returns (GetOrderResponse);
  rpc CreateOrder (CreateOrderRequest) returns (CreateOrderResponse);
}

message OrderItem {
  string id = 1;
  string product_id = 2;
  int32 quantity = 3;
  double price = 4;
}

message Order {
  string id = 1;
  string user_id = 2;
  string status = 3;
  repeated OrderItem items = 4;
  double total_amount = 5;
  string created_at = 6;
}

message GetOrderRequest {
  string id = 1;
}

message GetOrderResponse {
  Order order = 1;
}

message CreateOrderRequest {
  string user_id = 1;
  string cart_id = 2;
  string shipping_address = 3;
}

message CreateOrderResponse {
  Order order = 1;
}
