package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"strings"
	"time"

	authpb "github.com/marees-godev/GoCart-Server/contracts/protobuf/auth"
	merchantpb "github.com/marees-godev/GoCart-Server/contracts/protobuf/merchant"
	userpb "github.com/marees-godev/GoCart-Server/contracts/protobuf/user"
	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
	"github.com/marees-godev/GoCart-Server/pkg/auth"
	appErrors "github.com/marees-godev/GoCart-Server/pkg/errors"
	"github.com/marees-godev/GoCart-Server/pkg/grpcclient"
	"google.golang.org/grpc/metadata"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	if input.Email == "" || input.Password == "" {
		return nil, appErrors.BadRequest("email and password are required")
	}

	isMerchant := input.IsMerchant

	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return nil, appErrors.Internal(nil, "auth client unavailable")
	}

	res, err := authClient.Login(ctx, &authpb.LoginRequest{
		Email:      input.Email,
		Password:   input.Password,
		IsMerchant: isMerchant,
	})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	var userClient userpb.UserServiceClient
	if r.Clients != nil && r.Clients.UserClient != nil {
		userClient = r.Clients.UserClient
	} else if r.ClientMgr != nil && r.ClientMgr.UserClient != nil {
		userClient = r.ClientMgr.UserClient
	}

	var user *model.User
	if res.UserId != "" && !isMerchant && userClient != nil {
		uRes, _ := userClient.GetUser(ctx, &userpb.GetUserRequest{Id: res.UserId})
		if uRes != nil {
			user = toModelUser(uRes.User)
		}
	}
	if user == nil && res.UserId != "" {
		now := time.Now().UTC().Format(time.RFC3339)
		user = &model.User{
			ID:        res.UserId,
			Email:     input.Email,
			CreatedAt: &now,
		}
	}

	payload := &model.AuthPayload{
		Token: res.AccessToken,
		User:  user,
	}
	if res.RefreshToken != "" {
		refToken := res.RefreshToken
		payload.RefreshToken = &refToken
	}
	if res.TokenType != "" {
		tt := res.TokenType
		payload.TokenType = &tt
	}
	if res.ExpiresIn > 0 {
		exp := int(res.ExpiresIn)
		payload.ExpiresIn = &exp
	}
	role := string(model.RoleCustomer)
	if isMerchant {
		role = string(model.RoleMerchant)
	}
	if res.Role != "" {
		role = res.Role
	}
	if user != nil {
		user.Role = &role
		if res.FirstName != "" && user.FirstName == nil {
			fnStr := res.FirstName
			user.FirstName = &fnStr
		}
		if res.LastName != "" && user.LastName == nil {
			lnStr := res.LastName
			user.LastName = &lnStr
		}
	}

	if isMerchant {
		mID := res.MerchantId
		bEmail := input.Email
		if res.BusinessEmail != "" {
			bEmail = res.BusinessEmail
		}
		var firstName *string
		if res.FirstName != "" {
			fnStr := res.FirstName
			firstName = &fnStr
		} else if user != nil && user.FirstName != nil {
			firstName = user.FirstName
		}

		var lastName *string
		if res.LastName != "" {
			lnStr := res.LastName
			lastName = &lnStr
		} else if user != nil && user.LastName != nil {
			lastName = user.LastName
		}

		bName := ""
		if firstName != nil && lastName != nil {
			bName = strings.TrimSpace(*firstName + " " + *lastName)
		}
		if bName == "" {
			bName = input.Email
		}
		status := model.MerchantStatusPending

		var merchantClient merchantpb.MerchantServiceClient
		if r.ClientMgr != nil && r.ClientMgr.MerchantClient != nil {
			merchantClient = r.ClientMgr.MerchantClient
		}

		if merchantClient != nil && res.UserId != "" {
			mCtx := auth.WithUser(ctx, &auth.UserContext{
				UserID: res.UserId,
				Role:   string(model.RoleMerchant),
				Email:  input.Email,
			})
			mCtx = metadata.NewOutgoingContext(mCtx, metadata.Pairs(
				"x-user-id", res.UserId,
				"x-user-role", string(model.RoleMerchant),
			))
			mRes, _ := merchantClient.GetMerchant(mCtx, &merchantpb.GetMerchantRequest{Id: res.UserId})
			if mRes != nil && mRes.Merchant != nil {
				if mRes.Merchant.Id != "" {
					mID = mRes.Merchant.Id
				}
				if mRes.Merchant.BusinessEmail != "" {
					bEmail = mRes.Merchant.BusinessEmail
				}
				if mRes.Merchant.BusinessName != "" {
					bName = mRes.Merchant.BusinessName
				}
				status = model.MerchantStatus(mRes.Merchant.Status.String())
				if mRes.Merchant.FirstName != "" && firstName == nil {
					fn := mRes.Merchant.FirstName
					firstName = &fn
				}
				if mRes.Merchant.LastName != "" && lastName == nil {
					ln := mRes.Merchant.LastName
					lastName = &ln
				}
			}
		}

		payload.Merchant = &model.Merchant{
			ID:            mID,
			BusinessName:  bName,
			FirstName:     firstName,
			LastName:      lastName,
			BusinessEmail: &bEmail,
			Status:        status,
		}
	}

	return payload, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	if input.Email == "" || input.Password == "" {
		return nil, appErrors.BadRequest("email and password are required")
	}

	fn := ""
	if input.FirstName != nil {
		fn = *input.FirstName
	}
	ln := ""
	if input.LastName != nil {
		ln = *input.LastName
	}

	if fn == "" || ln == "" {
		return nil, appErrors.BadRequest("first_name and last_name are required")
	}

	isMerchant := input.IsMerchant

	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return nil, appErrors.Internal(nil, "auth client unavailable")
	}

	res, err := authClient.Register(ctx, &authpb.RegisterRequest{
		Email:      input.Email,
		Password:   input.Password,
		FirstName:  fn,
		LastName:   ln,
		IsMerchant: isMerchant,
	})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	var userClient userpb.UserServiceClient
	if r.Clients != nil && r.Clients.UserClient != nil {
		userClient = r.Clients.UserClient
	} else if r.ClientMgr != nil && r.ClientMgr.UserClient != nil {
		userClient = r.ClientMgr.UserClient
	}

	var user *model.User
	if res.UserId != "" && !isMerchant && userClient != nil {
		uRes, _ := userClient.GetUser(ctx, &userpb.GetUserRequest{Id: res.UserId})
		if uRes != nil {
			user = toModelUser(uRes.User)
		}
	}
	if user == nil && res.UserId != "" {
		now := time.Now().UTC().Format(time.RFC3339)
		user = &model.User{
			ID:        res.UserId,
			Email:     input.Email,
			FirstName: &fn,
			LastName:  &ln,
			CreatedAt: &now,
		}
	}

	payload := &model.AuthPayload{
		Token: res.AccessToken,
		User:  user,
	}
	if res.RefreshToken != "" {
		refToken := res.RefreshToken
		payload.RefreshToken = &refToken
	}
	if res.TokenType != "" {
		tt := res.TokenType
		payload.TokenType = &tt
	}
	if res.ExpiresIn > 0 {
		exp := int(res.ExpiresIn)
		payload.ExpiresIn = &exp
	}

	role := string(model.RoleCustomer)
	if isMerchant {
		role = string(model.RoleMerchant)
	}
	if res.Role != "" {
		role = res.Role
	}
	if user != nil {
		user.Role = &role
	}

	if isMerchant {
		mID := res.MerchantId
		bEmail := input.Email
		if res.BusinessEmail != "" {
			bEmail = res.BusinessEmail
		}
		var firstName *string
		if res.FirstName != "" {
			fnStr := res.FirstName
			firstName = &fnStr
		} else if fn != "" {
			firstName = &fn
		}

		var lastName *string
		if res.LastName != "" {
			lnStr := res.LastName
			lastName = &lnStr
		} else if ln != "" {
			lastName = &ln
		}

		bName := strings.TrimSpace(fn + " " + ln)
		if bName == "" {
			bName = input.Email
		}
		status := model.MerchantStatusPending
		payload.Merchant = &model.Merchant{
			ID:            mID,
			BusinessName:  bName,
			FirstName:     firstName,
			LastName:      lastName,
			BusinessEmail: &bEmail,
			Status:        status,
		}
	}

	return payload, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.AuthPayload, error) {
	if strings.TrimSpace(input.RefreshToken) == "" {
		return nil, appErrors.BadRequest("refresh_token is required")
	}

	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return nil, appErrors.Internal(nil, "auth client unavailable")
	}

	res, err := authClient.RefreshToken(ctx, &authpb.RefreshTokenRequest{
		RefreshToken: input.RefreshToken,
	})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	refToken := res.GetRefreshToken()
	tokenType := res.GetTokenType()
	expiresIn := int(res.GetExpiresIn())

	payload := &model.AuthPayload{
		Token:        res.GetAccessToken(),
		RefreshToken: &refToken,
		TokenType:    &tokenType,
		ExpiresIn:    &expiresIn,
	}
	if res.GetUserId() != "" {
		payload.User = &model.User{
			ID: res.GetUserId(),
		}
	}
	if payload.User != nil {
		if res.GetRole() != "" {
			roleStr := res.GetRole()
			payload.User.Role = &roleStr
		}
		if res.GetFirstName() != "" {
			fn := res.GetFirstName()
			payload.User.FirstName = &fn
		}
		if res.GetLastName() != "" {
			ln := res.GetLastName()
			payload.User.LastName = &ln
		}
	}
	if res.GetMerchantId() != "" {
		mID := res.GetMerchantId()
		var fnPtr, lnPtr *string
		if res.GetFirstName() != "" {
			fn := res.GetFirstName()
			fnPtr = &fn
		}
		if res.GetLastName() != "" {
			ln := res.GetLastName()
			lnPtr = &ln
		}
		bEmail := res.GetBusinessEmail()
		payload.Merchant = &model.Merchant{
			ID:            mID,
			FirstName:     fnPtr,
			LastName:      lnPtr,
			BusinessEmail: &bEmail,
		}
	}

	return payload, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.LogoutPayload, error) {
	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return nil, appErrors.Internal(nil, "auth client unavailable")
	}

	userCtx, authenticated := auth.FromContext(ctx)
	if !authenticated || userCtx == nil {
		return nil, appErrors.Unauthorized("authentication required for logout")
	}

	token := userCtx.RawToken
	if token == "" {
		token = userCtx.UserID
	}

	req := &authpb.LogoutRequest{
		AccessToken: token,
	}

	res, err := authClient.Logout(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	msg := res.GetMessage()
	return &model.LogoutPayload{
		Success: res.GetSuccess(),
		Message: &msg,
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, email string, otp string) (bool, error) {
	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return false, appErrors.Internal(nil, "auth client unavailable")
	}
	if email == "" || otp == "" {
		return false, appErrors.BadRequest("email and otp are required")
	}
	res, err := authClient.VerifyEmail(ctx, &authpb.VerifyEmailRequest{
		Email: email,
		Otp:   otp,
		Token: otp,
	})
	if err != nil {
		return false, grpcclient.TranslateGRPCError(err)
	}
	return res.GetSuccess(), nil
}

// ResendVerificationEmail is the resolver for the resendVerificationEmail field.
func (r *mutationResolver) ResendVerificationEmail(ctx context.Context, email string) (bool, error) {
	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return false, appErrors.Internal(nil, "auth client unavailable")
	}
	if email == "" {
		return false, appErrors.BadRequest("email is required")
	}
	res, err := authClient.ResendVerificationEmail(ctx, &authpb.ResendVerificationEmailRequest{
		Email: email,
	})
	if err != nil {
		return false, grpcclient.TranslateGRPCError(err)
	}
	return res.GetSuccess(), nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input model.ForgotPasswordInput) (*model.ForgotPasswordPayload, error) {
	if strings.TrimSpace(input.Email) == "" {
		return nil, appErrors.BadRequest("email is required")
	}

	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return nil, appErrors.Internal(nil, "auth client unavailable")
	}

	var clientIP string
	if ip, ok := ctx.Value("clientIP").(string); ok {
		clientIP = ip
	}

	res, err := authClient.ForgotPassword(ctx, &authpb.ForgotPasswordRequest{
		Email:      input.Email,
		ClientIp:   clientIP,
		IsMerchant: input.IsMerchant,
	})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	return &model.ForgotPasswordPayload{
		Success: res.GetSuccess(),
		Message: res.GetMessage(),
	}, nil
}

// ResetPasswordWithOtp is the resolver for the resetPasswordWithOtp field.
func (r *mutationResolver) ResetPasswordWithOtp(ctx context.Context, input model.ResetPasswordWithOtpInput) (*model.ResetPasswordPayload, error) {
	if strings.TrimSpace(input.Email) == "" {
		return nil, appErrors.BadRequest("email is required")
	}
	if strings.TrimSpace(input.Otp) == "" {
		return nil, appErrors.BadRequest("otp is required")
	}
	if input.NewPassword == "" {
		return nil, appErrors.BadRequest("newPassword is required")
	}

	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return nil, appErrors.Internal(nil, "auth client unavailable")
	}

	res, err := authClient.ResetPasswordWithOtp(ctx, &authpb.ResetPasswordWithOtpRequest{
		Email:       input.Email,
		Otp:         input.Otp,
		NewPassword: input.NewPassword,
		IsMerchant:  input.IsMerchant,
	})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	return &model.ResetPasswordPayload{
		Success: res.GetSuccess(),
		Message: res.GetMessage(),
	}, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (*model.ChangePasswordPayload, error) {
	userCtx, authenticated := auth.FromContext(ctx)
	if !authenticated || userCtx == nil || userCtx.UserID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	if input.OldPassword == "" {
		return nil, appErrors.BadRequest("oldPassword is required")
	}
	if input.NewPassword == "" {
		return nil, appErrors.BadRequest("newPassword is required")
	}

	var authClient authpb.AuthServiceClient
	if r.Clients != nil && r.Clients.AuthClient != nil {
		authClient = r.Clients.AuthClient
	} else if r.ClientMgr != nil && r.ClientMgr.AuthClient != nil {
		authClient = r.ClientMgr.AuthClient
	}

	if authClient == nil {
		return nil, appErrors.Internal(nil, "auth client unavailable")
	}

	res, err := authClient.ChangePassword(ctx, &authpb.ChangePasswordRequest{
		UserId:      userCtx.UserID,
		OldPassword: input.OldPassword,
		NewPassword: input.NewPassword,
	})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	return &model.ChangePasswordPayload{
		Success: res.GetSuccess(),
		Message: res.GetMessage(),
	}, nil
}
