package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
)

// AddToCart is the resolver for the addToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, input model.AddToCartInput) (*model.Cart, error) {
	panic(fmt.Errorf("not implemented: AddToCart - addToCart"))
}

// RemoveFromCart is the resolver for the removeFromCart field.
func (r *mutationResolver) RemoveFromCart(ctx context.Context, userID string, productID string) (*model.Cart, error) {
	panic(fmt.Errorf("not implemented: RemoveFromCart - removeFromCart"))
}

// ClearCart is the resolver for the clearCart field.
func (r *mutationResolver) ClearCart(ctx context.Context, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: ClearCart - clearCart"))
}

// Cart is the resolver for the cart field.
func (r *queryResolver) Cart(ctx context.Context, userID string) (*model.Cart, error) {
	panic(fmt.Errorf("not implemented: Cart - cart"))
}
