package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
)

// ReserveStock is the resolver for the reserveStock field.
func (r *mutationResolver) ReserveStock(ctx context.Context, orderID string, items []*model.ReservationItemInput) (*model.ReserveStockPayload, error) {
	panic(fmt.Errorf("not implemented: ReserveStock - reserveStock"))
}

// ReleaseStock is the resolver for the releaseStock field.
func (r *mutationResolver) ReleaseStock(ctx context.Context, reservationID string) (bool, error) {
	panic(fmt.Errorf("not implemented: ReleaseStock - releaseStock"))
}

// UpdateStock is the resolver for the updateStock field.
func (r *mutationResolver) UpdateStock(ctx context.Context, productID string, quantity int) (*model.StockItem, error) {
	panic(fmt.Errorf("not implemented: UpdateStock - updateStock"))
}

// Stock is the resolver for the stock field.
func (r *queryResolver) Stock(ctx context.Context, productID string) (*model.StockItem, error) {
	panic(fmt.Errorf("not implemented: Stock - stock"))
}
