package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
)

// CreateMerchant is the resolver for the createMerchant field.
func (r *mutationResolver) CreateMerchant(ctx context.Context, input model.CreateMerchantInput) (*model.Merchant, error) {
	panic(fmt.Errorf("not implemented: CreateMerchant - createMerchant"))
}

// UpdateMerchantStatus is the resolver for the updateMerchantStatus field.
func (r *mutationResolver) UpdateMerchantStatus(ctx context.Context, id string, status string) (*model.Merchant, error) {
	panic(fmt.Errorf("not implemented: UpdateMerchantStatus - updateMerchantStatus"))
}

// Merchant is the resolver for the merchant field.
func (r *queryResolver) Merchant(ctx context.Context, id string) (*model.Merchant, error) {
	panic(fmt.Errorf("not implemented: Merchant - merchant"))
}
