package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
)

// SendNotification is the resolver for the sendNotification field.
func (r *mutationResolver) SendNotification(ctx context.Context, input model.SendNotificationInput) (bool, error) {
	panic(fmt.Errorf("not implemented: SendNotification - sendNotification"))
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, userID string, limit *int, offset *int) (*model.NotificationList, error) {
	panic(fmt.Errorf("not implemented: Notifications - notifications"))
}
