package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
)

// RequestReturn is the resolver for the requestReturn field.
func (r *mutationResolver) RequestReturn(ctx context.Context, input model.RequestReturnInput) (*model.ReturnOrder, error) {
	panic(fmt.Errorf("not implemented: RequestReturn - requestReturn"))
}

// UpdateReturnStatus is the resolver for the updateReturnStatus field.
func (r *mutationResolver) UpdateReturnStatus(ctx context.Context, id string, status string) (*model.ReturnOrder, error) {
	panic(fmt.Errorf("not implemented: UpdateReturnStatus - updateReturnStatus"))
}

// ReturnOrder is the resolver for the returnOrder field.
func (r *queryResolver) ReturnOrder(ctx context.Context, id string) (*model.ReturnOrder, error) {
	panic(fmt.Errorf("not implemented: ReturnOrder - returnOrder"))
}
