package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	authpb "github.com/marees-godev/GoCart-Server/contracts/protobuf/auth"
	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/generated"
	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/grpc/pb/userpb"
	"github.com/marees-godev/GoCart-Server/pkg/auth"
	appErrors "github.com/marees-godev/GoCart-Server/pkg/errors"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	if r.Clients == nil {
		return nil, appErrors.Internal(nil, "clients unavailable")
	}
	if input.Email == "" || input.Password == "" {
		return nil, appErrors.BadRequest("email and password are required")
	}

	if r.Clients.AuthClient != nil {
		res, err := r.Clients.AuthClient.Login(ctx, &authpb.LoginRequest{
			Email:    input.Email,
			Password: input.Password,
		})
		if err != nil {
			return nil, err
		}
		var user *model.User
		if res.UserId != "" && r.Clients.UserClient != nil {
			uRes, _ := r.Clients.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: res.UserId})
			if uRes != nil {
				user = toModelUser(uRes.User)
			}
		}
		return &model.AuthPayload{
			Token: res.AccessToken,
			User:  user,
		}, nil
	}

	if r.Clients.UserClient != nil {
		res, err := r.Clients.UserClient.Login(ctx, &userpb.LoginRequest{
			Email:    input.Email,
			Password: input.Password,
		})
		if err != nil {
			return nil, err
		}
		return &model.AuthPayload{
			Token: res.Token,
			User:  toModelUser(res.User),
		}, nil
	}

	return nil, appErrors.Internal(nil, "auth client unavailable")
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	if r.Clients == nil {
		return nil, appErrors.Internal(nil, "clients unavailable")
	}
	if input.Email == "" || input.Password == "" {
		return nil, appErrors.BadRequest("email and password are required")
	}

	fn := ""
	if input.FirstName != nil {
		fn = *input.FirstName
	}
	ln := ""
	if input.LastName != nil {
		ln = *input.LastName
	}

	if r.Clients.AuthClient != nil {
		res, err := r.Clients.AuthClient.Register(ctx, &authpb.RegisterRequest{
			Email:     input.Email,
			Password:  input.Password,
			FirstName: fn,
			LastName:  ln,
		})
		if err != nil {
			return nil, err
		}
		var user *model.User
		if res.UserId != "" && r.Clients.UserClient != nil {
			uRes, _ := r.Clients.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: res.UserId})
			if uRes != nil {
				user = toModelUser(uRes.User)
			}
		}
		return &model.AuthPayload{
			Token: res.AccessToken,
			User:  user,
		}, nil
	}

	if r.Clients.UserClient != nil {
		res, err := r.Clients.UserClient.Register(ctx, &userpb.RegisterRequest{
			Email:     input.Email,
			Password:  input.Password,
			FirstName: fn,
			LastName:  ln,
		})
		if err != nil {
			return nil, err
		}
		return &model.AuthPayload{
			Token: res.Token,
			User:  toModelUser(res.User),
		}, nil
	}

	return nil, appErrors.Internal(nil, "auth client unavailable")
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "OK", nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	if r.Resolver.Version == "" {
		return "1.0.0", nil
	}
	return r.Resolver.Version, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	userId := ""
	if userCtx, ok := auth.UserFromContext(ctx); ok && userCtx != nil {
		userId = userCtx.UserID
	} else if legacyID, ok := ctx.Value("userID").(string); ok {
		userId = legacyID
	}

	if userId == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	res, err := r.Clients.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: userId})
	if err != nil {
		return nil, err
	}
	return toModelUser(res.User), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}
	if id == "" {
		return nil, appErrors.BadRequest("user id is required")
	}

	res, err := r.Clients.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return toModelUser(res.User), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
