package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	userpb "github.com/marees-godev/GoCart-Server/contracts/protobuf/user"
	"github.com/marees-godev/GoCart-Server/gateway/api-gateway/internal/graphql/model"
	"github.com/marees-godev/GoCart-Server/pkg/auth"
	appErrors "github.com/marees-godev/GoCart-Server/pkg/errors"
	"github.com/marees-godev/GoCart-Server/pkg/grpcclient"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}
	if authID != id {
		return nil, appErrors.BadRequest("user_id does not match the expected value")
	}

	firstName := ""
	if input.FirstName != nil {
		firstName = *input.FirstName
	}
	lastName := ""
	if input.LastName != nil {
		lastName = *input.LastName
	}
	phone := ""
	if input.Phone != nil {
		phone = *input.Phone
	}

	var gender *string
	if input.Gender != nil {
		g := input.Gender.String()
		gender = &g
	}

	req := &userpb.UpdateUserRequest{
		Id:             id,
		FirstName:      firstName,
		LastName:       lastName,
		Phone:          phone,
		Username:       input.Username,
		AlternatePhone: input.AlternatePhone,
		DateOfBirth:    input.DateOfBirth,
		Gender:         gender,
		Bio:            input.Bio,
		AvatarUrl:      input.AvatarURL,
	}
	res, err := r.Clients.UserClient.UpdateUser(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	return toModelUser(res.User), nil
}

// DeactivateAccount is the resolver for the deactivateAccount field.
func (r *mutationResolver) DeactivateAccount(ctx context.Context, input *model.DeactivateAccountInput) (*model.AccountActionResponse, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	var reason *string
	if input != nil && input.Reason != nil {
		reason = input.Reason
	}

	req := &userpb.DeactivateUserRequest{
		Id:     authID,
		Reason: reason,
	}

	res, err := r.Clients.UserClient.DeactivateUser(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	return &model.AccountActionResponse{
		Success: res.Success,
		Message: res.Message,
		Status:  res.Status,
	}, nil
}

// ReactivateAccount is the resolver for the reactivateAccount field.
func (r *mutationResolver) ReactivateAccount(ctx context.Context) (*model.AccountActionResponse, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	req := &userpb.ReactivateUserRequest{
		Id: authID,
	}

	res, err := r.Clients.UserClient.ReactivateUser(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	return &model.AccountActionResponse{
		Success: res.Success,
		Message: res.Message,
		Status:  res.Status,
	}, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, input *model.DeleteAccountInput) (*model.AccountActionResponse, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	var reason *string
	if input != nil && input.Reason != nil {
		reason = input.Reason
	}

	req := &userpb.DeleteUserRequest{
		Id:     authID,
		Reason: reason,
	}

	res, err := r.Clients.UserClient.DeleteUser(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}

	return &model.AccountActionResponse{
		Success: res.Success,
		Message: res.Message,
		Status:  res.Status,
	}, nil
}

// CreateUserAddress is the resolver for the createUserAddress field.
func (r *mutationResolver) CreateUserAddress(ctx context.Context, userID string, input model.CreateAddressInput) (*model.Address, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}
	if authID != userID {
		return nil, appErrors.BadRequest("user_id does not match the expected value")
	}

	label := ""
	if input.Label != nil {
		label = *input.Label
	}
	emailAddress := ""
	if input.EmailAddress != nil {
		emailAddress = *input.EmailAddress
	}
	isDefault := false
	if input.IsDefault != nil {
		isDefault = *input.IsDefault
	}

	req := &userpb.CreateUserAddressRequest{
		UserId:       userID,
		Label:        label,
		FullName:     input.FullName,
		PhoneNumber:  input.PhoneNumber,
		EmailAddress: emailAddress,
		AddressLine:  input.AddressLine,
		City:         input.City,
		State:        input.State,
		PostalCode:   input.PostalCode,
		Country:      input.Country,
		IsDefault:    isDefault,
	}

	res, err := r.Clients.UserClient.CreateUserAddress(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	return toModelAddress(res.Address), nil
}

// UpdateUserAddress is the resolver for the updateUserAddress field.
func (r *mutationResolver) UpdateUserAddress(ctx context.Context, id string, input model.UpdateAddressInput) (*model.Address, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	req := &userpb.UpdateUserAddressRequest{
		UserId:       authID,
		AddressId:    id,
		Label:        input.Label,
		FullName:     input.FullName,
		PhoneNumber:  input.PhoneNumber,
		EmailAddress: input.EmailAddress,
		AddressLine:  input.AddressLine,
		City:         input.City,
		State:        input.State,
		PostalCode:   input.PostalCode,
		Country:      input.Country,
		IsDefault:    input.IsDefault,
	}

	res, err := r.Clients.UserClient.UpdateUserAddress(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	return toModelAddress(res.Address), nil
}

// DeleteUserAddress is the resolver for the deleteUserAddress field.
func (r *mutationResolver) DeleteUserAddress(ctx context.Context, id string) (bool, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return false, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return false, appErrors.Unauthorized("authentication required")
	}

	req := &userpb.DeleteUserAddressRequest{
		UserId:    authID,
		AddressId: id,
	}

	res, err := r.Clients.UserClient.DeleteUserAddress(ctx, req)
	if err != nil {
		return false, grpcclient.TranslateGRPCError(err)
	}
	return res.Success, nil
}

// SetDefaultUserAddress is the resolver for the setDefaultUserAddress field.
func (r *mutationResolver) SetDefaultUserAddress(ctx context.Context, id string) (*model.Address, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	req := &userpb.SetDefaultUserAddressRequest{
		UserId:    authID,
		AddressId: id,
	}

	res, err := r.Clients.UserClient.SetDefaultUserAddress(ctx, req)
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	return toModelAddress(res.Address), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}

	userId := getAuthUserIDFromCtx(ctx)
	if userId == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	res, err := r.Clients.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: userId})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	user := toModelUser(res.User)
	if userCtx, ok := auth.UserFromContext(ctx); ok && userCtx != nil && user != nil && userCtx.Role != "" {
		rStr := userCtx.Role
		user.Role = &rStr
	}
	return user, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}
	if id == "" {
		return nil, appErrors.BadRequest("user id is required")
	}

	res, err := r.Clients.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: id})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	return toModelUser(res.User), nil
}

// UserAddresses is the resolver for the userAddresses field.
func (r *queryResolver) UserAddresses(ctx context.Context, userID string) ([]*model.Address, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}
	if userID == "" {
		return nil, appErrors.BadRequest("user id is required")
	}

	res, err := r.Clients.UserClient.ListUserAddresses(ctx, &userpb.ListUserAddressesRequest{UserId: userID})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	return toModelAddressList(res.Addresses), nil
}

// UserAddress is the resolver for the userAddress field.
func (r *queryResolver) UserAddress(ctx context.Context, id string) (*model.Address, error) {
	if r.Clients == nil || r.Clients.UserClient == nil {
		return nil, appErrors.Internal(nil, "user client unavailable")
	}
	if id == "" {
		return nil, appErrors.BadRequest("address id is required")
	}

	authID := getAuthUserIDFromCtx(ctx)
	if authID == "" {
		return nil, appErrors.Unauthorized("authentication required")
	}

	res, err := r.Clients.UserClient.GetUserAddress(ctx, &userpb.GetUserAddressRequest{
		UserId:    authID,
		AddressId: id,
	})
	if err != nil {
		return nil, grpcclient.TranslateGRPCError(err)
	}
	return toModelAddress(res.Address), nil
}
